# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4df0e7bc6ec49a6a3b70bf8cf014e06c"
name = "Magyx Bundle"
application_url = "https://magyx-bundle-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products,write_publications,write_discounts,read_metaobjects,read_metaobject_definitions"

[auth]
redirect_urls = [ "https://magyx-bundle-production.up.railway.app/api/auth" ]
